# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentinfo',
            table='student_info',
        ),
    ]
